# .gitlab-ci.yml
image:
  name: hashicorp/terraform:latest
  entrypoint:
    - /usr/bin/env
    - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - sh

variables:
  TF_ROOT: ${CI_PROJECT_DIR} # Assumes Terraform files are at project root
  TF_STATE_NAME: default
  TF_CACHE_KEY: default

cache:
  key: ${TF_CACHE_KEY}
  paths:
    - ${TF_ROOT}/.terraform

before_script:
  - cd ${TF_ROOT}
  - terraform --version
  - terraform init -backend-config="bucket=${S3_BUCKET_NAME}" -backend-config="region=${AWS_REGION}" -backend-config="key=${CI_PROJECT_PATH}/terraform.tfstate" # Example for S3 backend. S3_BUCKET_NAME and AWS_REGION should be CI/CD variables

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out=plan.tfplan
  artifacts:
    paths:
      - ${TF_ROOT}/plan.tfplan

apply:
  stage: apply
  script:
    - terraform apply -auto-approve plan.tfplan
  dependencies:
    - plan
  when: manual # Requires manual approval to run
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"' # Only allow apply on main branch for example
